import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomNavBar from "@/components/CustomNavBar";
import {Provider} from "react-redux";
import {store} from "@/redux/store";
import ReduxLayout from "@/components/ReduxLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ReduxLayout>
          <CustomNavBar />
          {children}
      </ReduxLayout>

      </body>
    </html>
  );
}
